name: Build with Rye
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2
      - name: config
        run: |
          rye config --set-bool behavior.use-uv=true
          rye symc --no-lock
      # - name: Build with Rye
      #   run: rye build
