name: Tests the examples in README
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2
      - name: Build with Rye
        run: rye run pytest tests/test_examples_readme.py
